/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    podcast: Podcast;
    knowledge: Knowledge;
    topics: Topic;
    projects: Project;
    resources: Resource;
    glossary: Glossary;
    timeline: Timeline;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    podcast: PodcastSelect<false> | PodcastSelect<true>;
    knowledge: KnowledgeSelect<false> | KnowledgeSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    glossary: GlossarySelect<false> | GlossarySelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 公开发布时间，必填。
   */
  date: string;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  category: string;
  series?: string | null;
  cover?: (number | null) | Media;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 用于构建提示、代码、图片、步骤、统计、对比表等更精致的展示区块。
   */
  contentBlocks?:
    | (
        | {
            variant: 'info' | 'tip' | 'warning' | 'danger';
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBlock';
          }
        | {
            language?: string | null;
            filename?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            file: number | Media;
            title?: string | null;
            duration?: string | null;
            /**
             * 可选；不填时播放器会直接使用音频文件地址。
             */
            downloadFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'audioBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            image: number | Media;
            alt: string;
            caption?: string | null;
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            content: string;
            author?: string | null;
            source?: string | null;
            url?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            src: string;
            title?: string | null;
            ratio?: ('16-9' | '4-3' | '1-1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embedBlock';
          }
        | {
            title?: string | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            columns?: number | null;
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statGridBlock';
          }
        | {
            caption?: string | null;
            columns: {
              key: string;
              label: string;
              highlight?: boolean | null;
              id?: string | null;
            }[];
            rows: {
              data:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'compareTableBlock';
          }
      )[]
    | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 用于无障碍阅读、SEO 和图片加载失败时的说明。
   */
  alt?: string | null;
  caption?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast".
 */
export interface Podcast {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 公开发布时间，必填。
   */
  date: string;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  episode: number;
  season?: number | null;
  /**
   * 上传到 media 集合；本地写入 MinIO，生产通过同一套配置写入阿里 OSS。
   */
  audioFile: number | Media;
  duration?: string | null;
  cover?: (number | null) | Media;
  transcript?: boolean | null;
  hosts?: string[] | null;
  guests?: string[] | null;
  timeline?:
    | {
        time: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  resources?:
    | {
        label: string;
        url?: string | null;
        /**
         * 外部链接和上传附件二选一。附件会进入 media 集合，由 MinIO/OSS 托管。
         */
        file?: (number | null) | Media;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 用于构建提示、代码、图片、步骤、统计、对比表等更精致的展示区块。
   */
  contentBlocks?:
    | (
        | {
            variant: 'info' | 'tip' | 'warning' | 'danger';
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBlock';
          }
        | {
            language?: string | null;
            filename?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            file: number | Media;
            title?: string | null;
            duration?: string | null;
            /**
             * 可选；不填时播放器会直接使用音频文件地址。
             */
            downloadFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'audioBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            image: number | Media;
            alt: string;
            caption?: string | null;
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            content: string;
            author?: string | null;
            source?: string | null;
            url?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            src: string;
            title?: string | null;
            ratio?: ('16-9' | '4-3' | '1-1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embedBlock';
          }
        | {
            title?: string | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            columns?: number | null;
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statGridBlock';
          }
        | {
            caption?: string | null;
            columns: {
              key: string;
              label: string;
              highlight?: boolean | null;
              id?: string | null;
            }[];
            rows: {
              data:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'compareTableBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge".
 */
export interface Knowledge {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 可选；不填写时不会作为强时间线内容处理。
   */
  date?: string | null;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  area:
    | 'ai-agent'
    | 'architecture'
    | 'data-engineering'
    | 'frontend'
    | 'product'
    | 'operations'
    | 'management'
    | 'tools';
  level?: ('basic' | 'intermediate' | 'advanced') | null;
  /**
   * 同一知识领域下的手动排序，数字越小越靠前。
   */
  order?: number | null;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 用于构建提示、代码、图片、步骤、统计、对比表等更精致的展示区块。
   */
  contentBlocks?:
    | (
        | {
            variant: 'info' | 'tip' | 'warning' | 'danger';
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBlock';
          }
        | {
            language?: string | null;
            filename?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            file: number | Media;
            title?: string | null;
            duration?: string | null;
            /**
             * 可选；不填时播放器会直接使用音频文件地址。
             */
            downloadFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'audioBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            image: number | Media;
            alt: string;
            caption?: string | null;
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            content: string;
            author?: string | null;
            source?: string | null;
            url?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            src: string;
            title?: string | null;
            ratio?: ('16-9' | '4-3' | '1-1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embedBlock';
          }
        | {
            title?: string | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            columns?: number | null;
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statGridBlock';
          }
        | {
            caption?: string | null;
            columns: {
              key: string;
              label: string;
              highlight?: boolean | null;
              id?: string | null;
            }[];
            rows: {
              data:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'compareTableBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 可选；不填写时不会作为强时间线内容处理。
   */
  date?: string | null;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  hero?: (number | null) | Media;
  /**
   * 填写关联内容的 slug 或 translationKey，用于专题聚合和后续推荐。
   */
  items?: string[] | null;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 用于构建提示、代码、图片、步骤、统计、对比表等更精致的展示区块。
   */
  contentBlocks?:
    | (
        | {
            variant: 'info' | 'tip' | 'warning' | 'danger';
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBlock';
          }
        | {
            language?: string | null;
            filename?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            file: number | Media;
            title?: string | null;
            duration?: string | null;
            /**
             * 可选；不填时播放器会直接使用音频文件地址。
             */
            downloadFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'audioBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            image: number | Media;
            alt: string;
            caption?: string | null;
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            content: string;
            author?: string | null;
            source?: string | null;
            url?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            src: string;
            title?: string | null;
            ratio?: ('16-9' | '4-3' | '1-1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embedBlock';
          }
        | {
            title?: string | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            columns?: number | null;
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statGridBlock';
          }
        | {
            caption?: string | null;
            columns: {
              key: string;
              label: string;
              highlight?: boolean | null;
              id?: string | null;
            }[];
            rows: {
              data:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'compareTableBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 可选；不填写时不会作为强时间线内容处理。
   */
  date?: string | null;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  role?: string | null;
  stack?: string[] | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 用于构建提示、代码、图片、步骤、统计、对比表等更精致的展示区块。
   */
  contentBlocks?:
    | (
        | {
            variant: 'info' | 'tip' | 'warning' | 'danger';
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBlock';
          }
        | {
            language?: string | null;
            filename?: string | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            file: number | Media;
            title?: string | null;
            duration?: string | null;
            /**
             * 可选；不填时播放器会直接使用音频文件地址。
             */
            downloadFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'audioBlock';
          }
        | {
            /**
             * 上传后自动由 media 集合生成访问地址。
             */
            image: number | Media;
            alt: string;
            caption?: string | null;
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            content: string;
            author?: string | null;
            source?: string | null;
            url?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            src: string;
            title?: string | null;
            ratio?: ('16-9' | '4-3' | '1-1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embedBlock';
          }
        | {
            title?: string | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            columns?: number | null;
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'statGridBlock';
          }
        | {
            caption?: string | null;
            columns: {
              key: string;
              label: string;
              highlight?: boolean | null;
              id?: string | null;
            }[];
            rows: {
              data:
                | {
                    [k: string]: unknown;
                  }
                | unknown[]
                | string
                | number
                | boolean
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'compareTableBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 可选；不填写时不会作为强时间线内容处理。
   */
  date?: string | null;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  type: 'tool' | 'book' | 'article' | 'video' | 'repo' | 'course';
  /**
   * 外部资料、站外文章、代码仓库、视频课程等继续填写链接。
   */
  url?: string | null;
  /**
   * 站内 PDF、图片、音频、文档等资源走上传附件，最终由 MinIO/OSS 托管。
   */
  asset?: (number | null) | Media;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary".
 */
export interface Glossary {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 可选；不填写时不会作为强时间线内容处理。
   */
  date?: string | null;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  aliases?: string[] | null;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: number;
  title: string;
  /**
   * 用于列表卡片、SEO 摘要和搜索结果，建议控制在 80 到 160 字。
   */
  description: string;
  /**
   * 用于前台路由和内容过滤。当前主站优先维护中文内容。
   */
  lang: 'zh-CN' | 'en';
  /**
   * 同一内容的不同语言版本使用相同 key；只写中文时也需要填写，方便未来扩展。
   */
  translationKey: string;
  /**
   * 用于生成页面 URL，建议使用小写英文、数字和短横线。
   */
  slug: string;
  /**
   * 只有“已发布”的内容会进入公开页面、RSS 和搜索入口。
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * 勾选后可用于首页、专题或重点内容区域的优先展示。
   */
  featured?: boolean | null;
  /**
   * 公开发布时间，必填。
   */
  date: string;
  /**
   * 内容有明显修订时再填写，用于前台展示更新时间。
   */
  updated?: string | null;
  /**
   * 用于筛选、搜索和相关内容推荐。技术名词可以保留英文原名。
   */
  tags?: string[] | null;
  kind?: ('milestone' | 'release' | 'learning') | null;
  /**
   * 适合录入连续正文；复杂展示结构建议使用下方“内容模块”。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'podcast';
        value: number | Podcast;
      } | null)
    | ({
        relationTo: 'knowledge';
        value: number | Knowledge;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'glossary';
        value: number | Glossary;
      } | null)
    | ({
        relationTo: 'timeline';
        value: number | Timeline;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  category?: T;
  series?: T;
  cover?: T;
  content?: T;
  contentBlocks?:
    | T
    | {
        calloutBlock?:
          | T
          | {
              variant?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        codeBlock?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        audioBlock?:
          | T
          | {
              file?: T;
              title?: T;
              duration?: T;
              downloadFile?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              content?: T;
              author?: T;
              source?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        embedBlock?:
          | T
          | {
              src?: T;
              title?: T;
              ratio?: T;
              id?: T;
              blockName?: T;
            };
        stepsBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statGridBlock?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        compareTableBlock?:
          | T
          | {
              caption?: T;
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    highlight?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast_select".
 */
export interface PodcastSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  episode?: T;
  season?: T;
  audioFile?: T;
  duration?: T;
  cover?: T;
  transcript?: T;
  hosts?: T;
  guests?: T;
  timeline?:
    | T
    | {
        time?: T;
        label?: T;
        id?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        url?: T;
        file?: T;
        note?: T;
        id?: T;
      };
  content?: T;
  contentBlocks?:
    | T
    | {
        calloutBlock?:
          | T
          | {
              variant?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        codeBlock?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        audioBlock?:
          | T
          | {
              file?: T;
              title?: T;
              duration?: T;
              downloadFile?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              content?: T;
              author?: T;
              source?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        embedBlock?:
          | T
          | {
              src?: T;
              title?: T;
              ratio?: T;
              id?: T;
              blockName?: T;
            };
        stepsBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statGridBlock?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        compareTableBlock?:
          | T
          | {
              caption?: T;
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    highlight?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge_select".
 */
export interface KnowledgeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  area?: T;
  level?: T;
  order?: T;
  content?: T;
  contentBlocks?:
    | T
    | {
        calloutBlock?:
          | T
          | {
              variant?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        codeBlock?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        audioBlock?:
          | T
          | {
              file?: T;
              title?: T;
              duration?: T;
              downloadFile?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              content?: T;
              author?: T;
              source?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        embedBlock?:
          | T
          | {
              src?: T;
              title?: T;
              ratio?: T;
              id?: T;
              blockName?: T;
            };
        stepsBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statGridBlock?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        compareTableBlock?:
          | T
          | {
              caption?: T;
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    highlight?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  hero?: T;
  items?: T;
  content?: T;
  contentBlocks?:
    | T
    | {
        calloutBlock?:
          | T
          | {
              variant?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        codeBlock?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        audioBlock?:
          | T
          | {
              file?: T;
              title?: T;
              duration?: T;
              downloadFile?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              content?: T;
              author?: T;
              source?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        embedBlock?:
          | T
          | {
              src?: T;
              title?: T;
              ratio?: T;
              id?: T;
              blockName?: T;
            };
        stepsBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statGridBlock?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        compareTableBlock?:
          | T
          | {
              caption?: T;
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    highlight?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  role?: T;
  stack?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  content?: T;
  contentBlocks?:
    | T
    | {
        calloutBlock?:
          | T
          | {
              variant?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        codeBlock?:
          | T
          | {
              language?: T;
              filename?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        audioBlock?:
          | T
          | {
              file?: T;
              title?: T;
              duration?: T;
              downloadFile?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              content?: T;
              author?: T;
              source?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        embedBlock?:
          | T
          | {
              src?: T;
              title?: T;
              ratio?: T;
              id?: T;
              blockName?: T;
            };
        stepsBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statGridBlock?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        compareTableBlock?:
          | T
          | {
              caption?: T;
              columns?:
                | T
                | {
                    key?: T;
                    label?: T;
                    highlight?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    data?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  type?: T;
  url?: T;
  asset?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary_select".
 */
export interface GlossarySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  aliases?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  lang?: T;
  translationKey?: T;
  slug?: T;
  status?: T;
  featured?: T;
  date?: T;
  updated?: T;
  tags?: T;
  kind?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}